server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    # Salud del contenedor
    location = /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    # briefs.cupula.com.ec/systems/<client>/...
    location /systems/ {
        try_files $uri $uri/ $uri/index.html =404;
    }

    location = / {
        return 302 /systems/leko/;
    }
}
